joint1:
  limit:
    lower:     -2.8973
    upper:      2.8973
    velocity:   21.750
    effort:    870.0

joint2:
  limit:
    lower:     -1.7628
    upper:      1.7628
    velocity:   21.750
    effort:    870.0

joint3:
  limit:
    lower:     -2.8973
    upper:      2.8973
    velocity:   21.750
    effort:    870.0

joint4:
  limit:
    lower:     -3.0718
    upper:     -0.0698
    velocity:   21.750
    effort:    870.0

joint5:
  limit:
    lower:     -2.8973
    upper:      2.8973
    velocity:   26.100
    effort:    120.0

joint6:
  limit:
    lower:     -0.0175
    upper:      3.7525
    velocity:   26.100
    effort:    120.0

joint7:
  limit:
    lower:     -2.8973
    upper:      2.8973
    velocity:   26.100
    effort:    120.0