controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
      - left_arm_joint7
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
  - name: fake_middle_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - middle_arm_joint1
      - middle_arm_joint2
      - middle_arm_joint3
      - middle_arm_joint4
      - middle_arm_joint5
      - middle_arm_joint6
      - middle_arm_joint7
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_finger_joint1
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_finger_joint1
  - name: fake_middle_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - middle_arm_finger_joint1
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: default
  - group: right_arm
    pose: default
  - group: middle_arm
    pose: default
  - group: left_hand
    pose: close
  - group: right_hand
    pose: close
  - group: middle_hand
    pose: close