controller_list:
  - name: right_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
  - name: middle_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - middle_arm_joint1
      - middle_arm_joint2
      - middle_arm_joint3
      - middle_arm_joint4
      - middle_arm_joint5
      - middle_arm_joint6
      - middle_arm_joint7
  - name: left_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
      - left_arm_joint7

  #notice that the gripper's joint2 mimics joint1
  #this is why it is not listed under the hand controllers

  - name: right_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - right_arm_finger_joint1

  - name: middle_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - middle_arm_finger_joint1

  - name: left_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - left_arm_finger_joint1